spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
#    open-in-view: false 영속성 컨텍스트 생존 범위 트랜잭션 내로 제한하는 옵션
logging:
  level:
    org.hibernate.SQL: debug
# org.hibernate.type: trace